Fix first boot command template (#12)

diff --git a/template/first_boot.j2 b/template/first_boot.j2
--- a/template/first_boot.j2
+++ b/template/first_boot.j2
@@ -1,18 +1,27 @@
 #!/bin/bash -ex
 
-# Define the FIRST_BOOT variable
-FIRST_BOOT=1
+first_boot_file="/etc/first_boot"
 
-# Check if FIRST_BOOT equals 1
-if [ "$FIRST_BOOT" -eq 1 ]; then
-    echo "Running first boot setup..."
+trap 'echo "Failed to run first boot setup!" >> /dev/serial0' EXIT
+
+# Check if /etc/first_boot exists
+if [ -f "$first_boot_file" ]; then
+
+    # remove /etc/first_boot
+    rm -f "$first_boot_file"
+    echo "Removing first boot file" >> /dev/serial0
+
+    echo "Running first boot setup..." >> /dev/serial0
 {% for command in commands %}
     {{ command }}{% endfor %}
 
-    # Modify this script to set FIRST_BOOT to 0
-    sed -i 's/FIRST_BOOT=1/FIRST_BOOT=0/' "$0"
-
-    echo "First boot setup completed."
+    echo "First boot setup completed." >> /dev/serial0
 fi
+
+trap - EXIT
+
+# remove /etc/first_boot
+rm -f "$first_boot_file"
+echo "Removing first boot file after failure" >> /dev/serial0
 
 exit 0
